version: "3.5"

services:

  app:
    image: portainer/portainer
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}/portainer:/data
    entrypoint: [/portainer, --no-auth]
    restart: on-failure

networks:
  traefik:
    external: true
